[API]
OPENROUTER_API_KEY = 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
OPENROUTER_API_ENDPOINT = "your-openrouter-endpoint"
OPENROUTER_API_MODEL_NAME = "your-openrouter-model-name"
